/* Monthly reconciliation: views only; edits use the existing transactional forms. */
(function(){
let pendingMonth=Core.today().slice(0,7),pendingKind='unfinished',pendingSty='';
const cents=n=>Math.round((Number(n)||0)*100);
function balance(a){const p=state.data.payments[a.id]||{};return {service:Math.max(0,cents(p.amount)-cents(p.paid))/100,retail:Math.max(0,(p.retailLines||[]).reduce((s,l)=>s+cents(l.amount),0)-cents(p.retailPaid))/100};}
function selectRows(kind,m,sty){const now=new Date(),today=Core.today(),time=String(now.getHours()).padStart(2,'0')+':'+String(now.getMinutes()).padStart(2,'0');return R('appointments').filter(a=>a.date.slice(0,7)===m&&(!sty||a.styId===sty)).filter(a=>{if(kind==='unfinished')return Core.active(a)&&a.status!=='completed'&&(a.date<today||(a.date===today&&a.time<=time));const b=balance(a);return a.status==='completed'&&(kind==='service'?b.service>0:b.service>0||b.retail>0);}).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));}
function entry(m,sty){return `<button type="button" class="pending-entry" data-action="pending-open" data-month="${E(m)}" data-sty="${E(sty)}"><strong>待處理</strong><span>${E(m)} · 待完成 ${selectRows('unfinished',m,sty).length} 筆${isAdmin()?' · 待收款 '+selectRows('unpaid',m,sty).length+' 筆':''}</span><small>按月份找卡片，補登完成與收款 ›</small></button>`;}
window.renderPending=function(){if(!isAdmin()&&pendingKind!=='unfinished')pendingKind='unfinished';const list=selectRows(pendingKind,pendingMonth,pendingSty);$('#brand').textContent='待處理';$('#content').innerHTML=`<div class="toolbar"><h1>每月待處理</h1><button data-page="calendar">返回月曆</button></div><div class="filters"><label>月份 <input type="month" id="pending-month" value="${E(pendingMonth)}"></label><select id="pending-sty" aria-label="待處理設計師"><option value="">所有設計師</option>${options(R('stylists'),pendingSty)}</select></div><div class="pending-tabs"><button data-action="pending-kind" data-id="unfinished" aria-pressed="${pendingKind==='unfinished'}">待完成 ${selectRows('unfinished',pendingMonth,pendingSty).length}</button>${isAdmin()?`<button data-action="pending-kind" data-id="unpaid" aria-pressed="${pendingKind!=='unfinished'}">待收款 ${selectRows('unpaid',pendingMonth,pendingSty).length}</button>`:''}</div><p class="hint">${pendingKind==='unfinished'?'只列已到預約開始時間、尚未完成的紀錄；取消、未到及未來預約不列入。':pendingKind==='service'?'目前列出已完成、服務金額尚未收齊的紀錄。':'只列已完成，服務或商品尚有未登記收款的紀錄；不代表客人一定欠款。'}</p><p>${list.length} 筆待核對 · 點卡片可修改，金額按鈕可補登收款。</p><div class="pending-cards">${list.map(a=>{const b=balance(a);return `<section><h2>${E(a.date)} · ${E(nameOf('stylists',a.styId))}</h2>${isAdmin()?`<p class="hint">服務待收 $${F(b.service)} · 商品待收 $${F(b.retail)}</p>`:''}${quickCard(a)}</section>`;}).join('')||'<div class="empty">這個月份與篩選條件沒有待處理紀錄。</div>'}</div>`;$('#pending-month').onchange=e=>{if(/^\d{4}-\d{2}$/.test(e.target.value)){pendingMonth=e.target.value;renderPending();}};$('#pending-sty').onchange=e=>{pendingSty=e.target.value;renderPending();};};
actions['pending-open']=(_,button)=>{pendingMonth=button?.dataset.month||month;pendingSty=button?.dataset.sty||'';pendingKind=button?.dataset.kind||'unfinished';page='pending';render();$('#content').scrollTop=0;};
actions['pending-kind']=kind=>{pendingKind=kind;renderPending();};
const cal=renderCalendar;renderCalendar=function(){cal();$('#content').insertAdjacentHTML('afterbegin',entry(month,styFilter));};
const day=renderDay;renderDay=function(){day();$('#content').insertAdjacentHTML('afterbegin',entry(selectedDate.slice(0,7),styFilter));};
const stats=renderStats;renderStats=function(){stats();if(!isAdmin())return;$('#content').insertAdjacentHTML('afterbegin',entry(statsFrom.slice(0,7),statsSty));const metric=[...document.querySelectorAll('.metric')].find(x=>x.querySelector('small')?.textContent==='已完成未收款');if(metric){const button=document.createElement('button');button.type='button';button.className='metric pending-metric';button.dataset.action='pending-open';button.dataset.month=statsFrom.slice(0,7);button.dataset.sty=statsSty;button.dataset.kind='service';button.innerHTML=metric.innerHTML+'<small>查看當月服務待收卡片 ›</small>';metric.replaceWith(button);}};
window.AetherPending={selectRows,balance};
})();
