(function(){
if(location.origin!=='https://jun051873-art.github.io'||!/^\/uuuuuuuuuuu\/(?:index.html)?$/.test(location.pathname))return;
const B=window.AetherPosBridge;
const total=p=>(p?.retailLines||[]).reduce((n,l)=>n+B.money(l.amount),0)/100;
function editRetail(id){checkWritable();requireAdmin();const p=Core.clone(state.data.payments[id]);if(!p)throw Error('請先保存預約');let lines=Core.clone(p.retailLines||[]);const catalogue=()=>state.data.settings.main.retailCatalogue||[];
openDialog('販賣商品與收款',`<p>服務金額另行記錄。每款商品請填完整名稱／規格，例如「髮蠟 A・80g」。金額是這一列的實際售價合計。</p><div id="retail-lines"></div><button type="button" id="retail-add">＋ 新增商品</button><p id="retail-total"></p>${field('商品已收金額',inp('retailPaid',p.retailPaid||0,'number','min="0" step="0.01" required'))}<button type="button" id="retail-full">商品已全額收款</button><p class="hint">儲存後會保留品項供下次選用；傳送到POS時仍須核對商品成本、庫存與對應項目。</p>`,async fd=>{const form=$('#dialog-form'),els=[...form.querySelectorAll('[data-retail-row]')];lines=els.map(el=>{const name=el.querySelector('[data-name]').value.trim(),qty=Number(el.querySelector('[data-qty]').value),amount=B.money(el.querySelector('[data-amount]').value)/100;if(!name||name.length>100||!Number.isInteger(qty)||qty<1||qty>100)throw Error('請填寫商品名稱與1–100的整數數量');const previous=lines.find(l=>l.id===el.dataset.retailRow);return {id:previous.id,productId:previous.name===name?previous.productId:(catalogue().find(x=>B.norm(x.name)===B.norm(name))?.id||Core.uid()),name,qty,amount};});const paid=B.money(fd.get('retailPaid'))/100,sum=total({retailLines:lines});if(paid>sum)throw Error('商品已收金額不可超過商品合計');await commit(d=>{assertCurrent(d,'payments',id,p);d.payments[id]={...p,retailLines:lines,retailPaid:paid};const defs=[...(d.settings.main.retailCatalogue||[])];for(const l of lines)if(!defs.some(x=>x.id===l.productId))defs.push({id:l.productId,name:l.name});d.settings.main.retailCatalogue=defs;},'商品明細與收款已保存');});
const readRows=()=>{lines=[...document.querySelectorAll('[data-retail-row]')].map(el=>({...lines.find(l=>l.id===el.dataset.retailRow),name:el.querySelector('[data-name]').value,qty:el.querySelector('[data-qty]').value,amount:el.querySelector('[data-amount]').value}));};
const paint=()=>{$('#retail-lines').innerHTML=lines.map(l=>`<div data-retail-row="${E(l.id)}" class="panel">${field('商品名稱／規格',`<input data-name list="retail-catalogue" value="${E(l.name)}" maxlength="100" required>`)}${field('數量',`<input data-qty type="number" value="${E(l.qty)}" min="1" max="100" step="1" required>`)}${field('這款實際售價合計',`<input data-amount type="number" value="${E(l.amount)}" min="0" step="0.01" required>`)}<button type="button" data-retail-remove="${E(l.id)}">移除此商品</button></div>`).join('')+`<datalist id="retail-catalogue">${catalogue().map(x=>`<option value="${E(x.name)}"></option>`).join('')}</datalist>`;document.querySelectorAll('[data-retail-remove]').forEach(b=>b.onclick=()=>{readRows();lines=lines.filter(l=>l.id!==b.dataset.retailRemove);paint();});$('#retail-lines').oninput=()=>{readRows();summary();};summary();};
const summary=()=>{$('#retail-total').textContent='商品合計 $'+F(lines.reduce((n,l)=>n+(Number(l.amount)||0),0));};$('#retail-add').onclick=()=>{readRows();lines.push({id:Core.uid(),productId:Core.uid(),name:'',qty:1,amount:0});paint();};$('#retail-full').onclick=()=>{readRows();$('#dialog-form').elements.retailPaid.value=lines.reduce((n,l)=>n+(Number(l.amount)||0),0);};paint();}
actions['retail-edit']=id=>{try{editRetail(id);}catch(e){toast(e.message,true);}};
const prior=quickCard;quickCard=function(a){let h=prior(a);if(isAdmin()){const p=state.data.payments[a.id],lines=p?.retailLines||[];h=h.replace('<div class="quick-payment">',`<button class="apt-services quick-surface" data-action="retail-edit" data-id="${E(a.id)}">${lines.length?lines.map(l=>E(l.name)+' ×'+l.qty).join('、'):'＋ 販賣商品'}<small>商品 $${F(total(p))} · 商品已收 $${F(p?.retailPaid||0)}</small></button><div class="quick-payment">`);}return h;};
const priorStats=renderStats;renderStats=function(){priorStats();if(!isAdmin())return;const data=Core.stats(state.data,statsFrom,statsTo,statsSty),retail=data.completed.reduce((n,a)=>n+total(state.data.payments[a.id]),0),paid=data.completed.reduce((n,a)=>n+(state.data.payments[a.id]?.retailPaid||0),0);document.querySelector('.stats-space')?.insertAdjacentHTML('afterbegin',`<section class="panel"><h3>服務與販賣分開統計</h3><p>服務 $${F(data.revenue)} · 商品 $${F(retail)} · 合計 $${F(data.revenue+retail)}</p><p>服務已收 $${F(data.paid)} · 商品已收 $${F(paid)}</p><small>依目前日期與人員篩選，只計已完成預約；商品不算進服務業績。</small></section>`);};
})();
